import { createApp } from "vue";
import "mdui/mdui.css";
import "mdui/components/button.js";
import "mdui/components/text-field.js";
import "mdui/components/select.js";
import "mdui/components/menu-item.js";
import "mdui/components/slider.js";
import "mdui/components/checkbox.js";
import "mdui/components/switch.js";
import "mdui/components/button-icon.js";
import "mdui/components/tabs.js";
import "mdui/components/tab.js";
import "mdui/components/tab-panel.js";
import "mdui/components/linear-progress.js";
import { setColorScheme } from "mdui/functions/setColorScheme.js";
import App from "./App.vue";
import "./styles.css";
import "./styles/timing.css";

setColorScheme("#01cff0");
createApp(App).mount("#app");
